INSERT INTO ACADEMIC_DEGREES (ID, NAME) VALUES (1, 'Systems Engineer');
INSERT INTO ACADEMIC_DEGREES (ID, NAME) VALUES (2, 'Software Engineer');
INSERT INTO ACADEMIC_DEGREES (ID, NAME) VALUES (3, 'Web Designer');
INSERT INTO ACADEMIC_DEGREES (ID, NAME) VALUES (4, 'Systems Analyst');

INSERT INTO COMPANIES (ID, NAME, PHONE) VALUES (1, 'Noesis', '654321546');
INSERT INTO COMPANIES (ID, NAME, PHONE) VALUES (2, 'Empresa A', '65404154567');
INSERT INTO COMPANIES (ID, NAME, PHONE) VALUES (3, 'Empresa B', '54621043517');
INSERT INTO COMPANIES (ID, NAME, PHONE) VALUES (4, 'Empresa C', '89739150678');

INSERT INTO SKILLS (ID, SKILL) VALUES (1, 'Java');
INSERT INTO SKILLS (ID, SKILL) VALUES (2, 'C++');
INSERT INTO SKILLS (ID, SKILL) VALUES (3, '.NET');
INSERT INTO SKILLS (ID, SKILL) VALUES (4, 'Phyton');